set a as input("Enter number 1: ")
set op as input("Enter operator: ")
set b as input("Enter number 2: ")

if(op = "+")
{
	print(a " + " b " = " add(a b))
}

if(op = "-")
{
	print(a " - " b " = " subtract(a b))
}

if(op = "*")
{
	print(a " * " b " = " multiply(a b))
}

if(op = "/")
{
	print(a " / " b " = " divide(a b))
}

if(op = "^")
{
	print(a " ^ " b " = " power(a b))
}

if(op = "^")
{
	print(a " ^ " b " = " power(a b))
}

else
{
	print("Illegal operation")
}